### ISSUE TITLE
`no-notes` is not always detected as not-a-note?

### ISSUE THREAD

**Issue by ckerr** [electron/clerk#33]
https://github.com/electron/electron/pull/17947#issuecomment-486719316 reads

> **Release Notes Persisted**
>
> no-notes 

But should have been:

> **No Release Notes**

**Comment by MarshallOfSound** [comment]
That isn't just `no-notes`

![image](https://user-images.githubusercontent.com/6634592/67239552-4d927080-f404-11e9-8e70-132be1dfa32a.png)

I believe you fixed this here https://github.com/electron/clerk/commit/b717742415dde00e184e773b4a1e24192a80ea87 but missed a small thing, PR incoming
